sudo: required
os: linux
language: android

android:
  components:
    - build-tools-28.0.3
    - android-28

before_install:
  - pwd
  - ls -la
  - chmod +x /home/travis/build/14607/FTC_14607/gradlew
  - sudo touch ~/.android/repositories.cfg
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update


 script:
  - ./gradlew clean
  - ./gradlew assembleDebug
  - ./gradlew assembleDebugAndroidTest
