sudo: required
language: android

android:
  components:
    # Update Android SDK Tools
    - tools
    - build-tools-28.0.1
    - android-28
    
env:
  - CI=true

before_install:
  - sudo chmod +x gradlew
  - sudo touch ~/.android/repositories.cfg
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  
script:
  - ./gradlew clean
  - ./gradlew assembleDebug
  - ./gradlew assembleDebugAndroidTest
