language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

env:
  - CI=true

script:
  - ./gradlew build -x signArchives -s
  - chmod +x ./gradlew

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/dists/

android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-23.0.1
    - android-23

    # Support library
    - extra-android-support
    - extra-android-m2repository
