sudo: required
language: android

env:
  - CI=true

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"


  
android:
  components:
    # Update Android SDK Tools
    - tools
    - build-tools-28.0.1
    - android-28

script:
  - chmod +x ./gradlew
  - ./gradlew clean
  - ./gradlew assembleDebug
  - ./gradlew assembleDebugAndroidTest
  - ./gradlew build
